specVersion: 0.0.1
description: The project for getting the on chain data of Kusama
repository: "https://github.com/parallel-finance/auction-subquery"
schema: ./schema.graphql
network:
  endpoint: wss://regnet-relay-rpc.parallel.fi
  # endpoint: wss://staging-rpc.parallel.fi
  # endpoint: wss://rpc.polkadot.io
  # dictionary: "https://api.subquery.network/sq/subquery/dictionary-kusama"
dataSources:
  - name: app
    kind: substrate/Runtime
    startBlock: 7559000
    # startBlock: 162370
    mapping:
      handlers:
        - handler: handleTermsForAllProjects
          kind: substrate/CallHandler
          filter:
            module: utility
            method: signAndSend
            success: true
        - handler: handleBatchAll
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
            success: true
        - handler: handleMoonbeamContribute
          kind: substrate/EventHandler
          filter:
            module: crowdloan
            method: Contributed
        - handler: hotfixScript
          kind: substrate/BlockHandler
