specVersion: 0.0.1
description: The project for getting the on chain data of Kusama
repository: "https://github.com/parallel-finance/auction-subquery"
schema: ./schema.graphql
network:
  endpoint: wss://regnet-relay-rpc.parallel.fi
dataSources:
  - name: app
    kind: substrate/Runtime
    startBlock: 7559000
    mapping:
      handlers:
        - handler: handleBatchAll
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
            success: true
